name: Publish - Play store

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-play-store:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 60

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Load Google Play Distribution File
        env:
          PLAY_STORE_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_BASE64 }}
        run: echo $PLAY_STORE_KEY | base64 -di > play_publish.json

      - name: Load Firebase Distribution File
        env:
          SIGNING: ${{ secrets.SIGNING_PROPERTIES_FILE_BASE64 }}
        run: echo $SIGNING | base64 -di > credentials.properties

      - name: Load Keystore
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEYSTORE_FILE_BASE64 }}
        run: echo $KEYSTORE | base64 -di > android_keystore.jks
        
      - name: Setting environment values
        env:
          PLAYSTORE_TRACK: "production"
          PLAYSTORE_RELEASE_STATUS: "completed"

      - name: Deploy Play Store Beta
        run: |
            ./gradlew --no-configuration-cache publishReleaseBundle uploadCrashlyticsMappingFileRelease
